### ISSUE TITLE
COMMIT_TEMPLATE env var not used

### ISSUE THREAD

**Issue by proskehy** [justinbarrick/fluxcloud#23] opened 2019-01-31 08:33 UTC
When trying to use fluxcloud notifications with a private bitbucket-based repository, the COMMIT_TEMPLATE does not seem to do anything.

From the `kubectl describe pod` command:
```
Environment:
  ...
  COMMIT_TEMPLATE:   {{ .VCSLink }}/commits/{{ .Commit }}
```

 Resulting link in the notification (with placeholder words for the domain and project/repo): http://git.private.com/projects/myproject/repos/my-flux-repo/commit/sha 

Edit: not sure if I should create a separate issue for that, but when I change the chart in my flux repo, no notification is sent, though the event can be seen in the fluxcloud logs, is that an intentional behaviour?

**Comment by jbarrick-mesosphere** [comment] 2019-01-31 21:36
Which version of fluxcloud are you running?

**Comment by proskehy** [comment] 2019-01-31 21:39
I took the yaml file from the examples folder, so that should be fluxcloud:v0.3.0.

**Comment by proskehy** [comment] 2019-02-05 12:33
@jbarrick-mesosphere Update: the template IS actually used. I was just looking for it in the wrong place.

I took a proper look at the JSON structure representing the notification and the template is applied in the `title_link` field, but not in the `text` field. 

Looking at the code, I see that the issue lies in the hardcoded link format in the `body_template`. I see that it is customizable, so I guess I could just replace the whole `body_template` with the correct link format, but I was thinking it might be more intuitive that the `commit_template` change somehow applies into the default `body_template` too. 

However, I wasn't able to figure out a smart way of incorporating this into the code (I've never used Go before, so I'm probably not the best person to be looking into that, but I wanted to try). Do you have any ideas on how this can be achieved?

**Comment by mobsikx** [comment] 2019-05-21 13:25
`grep -HRi '/commit' * | grep -v '\.md:'
chart/templates/deployment.yaml:            value: "{{ .VCSLink }}/commits/{{ .Commit }}"
chart/values.yaml:      commitTemplate: "{{ .VCSLink }}/commits/{{ .Commit }}"`

I would expect then see in the logs commits instead of commit, however this is the result:
`klf -c fluxcloud flux-5c697f999f-t9s2z | grep -oE 'https://.*/commit/.*' | awk -F '/' '{ print $8 }' | sort -u
commit`

**Comment by mobsikx** [comment] 2019-05-31 09:08
The problem is that you set it as const:
`const (
        titleTemplate = ...
        bodyTemplate  = ...
        commitTemplate = ...
)`

and after that you try to assign another value to it which won't work for obvious reason, it's a const, right:
`commitTemplate := config.Optional("commit_template", commitTemplate)`

**Comment by jseiser** [comment] 2019-11-06 20:29
Same issue, here.  The Link to the commit in the title is correct, but not in the body.

`	bodyTemplate  = `
Event: {{ .EventString }}
{{ if and (ne .EventType "commit") (gt (len .Commits) 0) }}Commits:
{{ range .Commits }}
* {{ call $.FormatLink (print $.VCSLink "/commit/" .Revision) (truncate .Revision 7) }}: {{ .Message }}
{{end}}{{end}}
{{ if (gt (len .EventServiceIDs) 0) }}Resources updated:
{{ range .EventServiceIDs }}
* {{ . }}
{{ end }}{{ end }}
{{ if gt (len .Errors) 0 }}Errors:
{{ range .Errors }}
Resource {{ .ID }}, file: {{ .Path }}:
> {{ .Error }}
{{ end }}{{ end }}
``

Is it possible to overwrite this from the helm chart?

**Comment by proskehy** [comment] 2019-11-07 13:56
@jseiser how are you deploying with Helm?

I'm using the deployment from `examples/fluxcloud.yaml` and I just modified it by adding the env var:
```
        - name: BODY_TEMPLATE
          value: |
            Event: {{ .EventString }}
            {{ if and (ne .EventType "commit") (gt (len .Commits) 0) }}Commits:
            {{ range .Commits }}
            * {{ call $.FormatLink (print $.VCSLink "/commits/" .Revision) (truncate .Revision 7) }}: {{ .Message }}
            {{end}}{{end}}
            {{ if (gt (len .EventServiceIDs) 0) }}Resources updated:
            {{ range .EventServiceIDs }}
            * {{ . }}
            {{ end }}{{ end }}
            {{ if gt (len .Errors) 0 }}Errors:
            {{ range .Errors }}
            Resource {{ .ID }}, file: {{ .Path }}:

            > {{ .Error }}
            {{ end }}{{ end }}
```

**Comment by jseiser** [comment] 2019-11-07 19:09
@proskehy 

This fixed it, I wasnt doing the `value: |` correctly.

**Comment by justinbarrick** [comment] 2019-11-07 19:10
Are there any remaining issues here or should we close this?

**Comment by proskehy** [comment] 2019-11-07 20:18
@jseiser glad to hear that! :) 
@justinbarrick I think we can close this (mentioning this in the readme would probably be a good idea)

**Comment by justinbarrick** [comment] 2019-11-07 20:21
Agreed. Always happy to approve pull requests.

**Closed** 2019-11-07 20:23 UTC
